-- MySQL Script generated by MySQL Workbench
-- Thu 07 Dec 2017 12:10:35 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `short` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`state` ;

CREATE TABLE IF NOT EXISTS `mydb`.`state` (
  `id` INT NOT NULL,
  `country_id` INT NOT NULL,
  `name` VARCHAR(127) NULL,
  `short` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_state_country_idx` (`country_id` ASC),
  CONSTRAINT `fk_state_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`person` ;

CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `short` VARCHAR(45) NULL,
  `sex` TINYINT NULL,
  `birthday` DATE NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`party` ;

CREATE TABLE IF NOT EXISTS `mydb`.`party` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `short` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`source` ;

CREATE TABLE IF NOT EXISTS `mydb`.`source` (
  `id` INT NOT NULL,
  `title` VARCHAR(63) NULL,
  `description` VARCHAR(127) NULL,
  `url` VARCHAR(511) NULL,
  `created` TIMESTAMP NULL,
  `updated` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`term`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`term` ;

CREATE TABLE IF NOT EXISTS `mydb`.`term` (
  `id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `from` DATE NULL,
  `until` DATE NULL,
  `votes` INT NULL,
  `active` TINYINT(1) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_term_congressmen1_idx` (`person_id` ASC),
  CONSTRAINT `fk_term_congressmen1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`city` ;

CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `short` VARCHAR(45) NULL,
  `population` INT NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_state1_idx` (`state_id` ASC),
  CONSTRAINT `fk_city_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `mydb`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `office` VARCHAR(45) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `id` INT NOT NULL,
  `term_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `active` TINYINT(1) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_term1_idx` (`term_id` ASC),
  INDEX `fk_contact_address1_idx` (`address_id` ASC),
  INDEX `fk_contact_congressmen1_idx` (`person_id` ASC),
  CONSTRAINT `fk_contact_term1`
    FOREIGN KEY (`term_id`)
    REFERENCES `mydb`.`term` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_congressmen1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`info` (
  `id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  `type` ENUM('phone', 'email') NULL,
  `value` VARCHAR(127) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_info_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_info_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subject` (
  `id` INT NOT NULL,
  `title` VARCHAR(127) NULL,
  `description` TEXT NULL,
  `date` DATE NULL,
  `score` INT NULL,
  `positive` INT NULL,
  `negative` INT NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`related`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`related` ;

CREATE TABLE IF NOT EXISTS `mydb`.`related` (
  `id` INT NOT NULL,
  `news_id` INT NOT NULL,
  `party_id` INT NOT NULL,
  `subject_id` INT NULL,
  `person_id` INT NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_related_congressmen1_idx` (`person_id` ASC),
  INDEX `fk_related_party1_idx` (`party_id` ASC),
  INDEX `fk_related_news1_idx` (`news_id` ASC),
  INDEX `fk_related_subject1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_related_congressmen1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_related_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `mydb`.`party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_related_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `mydb`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_related_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orientation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orientation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orientation` (
  `id` INT NOT NULL,
  `party_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `mandatory` TINYINT(1) NULL,
  `punishment` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favor_party1_idx` (`party_id` ASC),
  INDEX `fk_favor_subject1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_favor_party1`
    FOREIGN KEY (`party_id`)
    REFERENCES `mydb`.`party` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favor_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`score` ;

CREATE TABLE IF NOT EXISTS `mydb`.`score` (
  `id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  `in_favor` TINYINT(1) NULL,
  `created` TIMESTAMP NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_score_subject1_idx` (`subject_id` ASC),
  INDEX `fk_score_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_score_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `mydb`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_score_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
